<form id="nsu-coupon-form" action="<?php echo $this->getUrl('nsu/index/couponPost') ?>" method="post">
    <div class="discount">
        <h2><?php echo $this->__('NSU Discount') ?></h2>
        <div class="nsu-discount-form">
            <label for="coupon_code"><?php echo $this->__('Enter your NSU Id if you have one.') ?></label>
            <input type="hidden" name="remove-nsu" id="remove-coupone-nsu" value="0" />
            <div class="input-box">
                <input class="input-text" id="coupon_code_nsu" name="coupon_code_nsu" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
            </div>
            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Validate') ?>" class="button" onclick="nsudiscountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Validate') ?></span></span></button>
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" onclick="nsudiscountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
var nsudiscountForm = new VarienForm('nsu-coupon-form');
nsudiscountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code_nsu').removeClassName('required-entry');
        $('remove-coupone-nsu').value = "1";
    } else {
        $('coupon_code_nsu').addClassName('required-entry');
        $('remove-coupone-nsu').value = "0";
    }
    return VarienForm.prototype.submit.bind(nsudiscountForm)();
}
//]]>
</script>
            <?php
                
                /*
                    This shows how to load specific fields from a record in the database.
                    1) Note the load(15), this corresponds to saying "select * from table where table_id = 15"
                    2) You can then just use the get(fieldname) to pull specific data from the table.
                    3) If you have a field named news_id, then it becomes getNewsId, etc.
                */
                /*
                $news = Mage::getModel('nsu/nsu')->load(15);
                echo $news->getNewsId();
                echo $news->getTitle();
                echo $news->getContent();
                echo $news->getStatus();
                */
                
                /*
                    This shows an alternate way of loading datas from a record using the database the "Magento Way" (using blocks and controller).
 					Uncomment blocks in /app/code/local/Namespace/Module/controllers/IndexController.php if you want to use it.

               */
                /*
                $object = $this->getNSU();
                echo 'id: '.$object['test_id'].'<br/>';
				echo 'title: '.$object['title'].'<br/>';
				echo 'content: '.$object['content'].'<br/>';
				echo 'status: '.$object['status'].'<br/>';
                */            
            
            
                /*
                    This shows how to load multiple rows in a collection and save a change to them.
                    1) The setPageSize function will load only 5 records per page and you can set the current Page with the setCurPage function.
                    2) The $collection->walk('save') allows you to save everything in the collection after all changes have been made.
                */
                /*
                $i = 0;
                
                $collection = Mage::getModel('nsu/nsu')->getCollection();
                $collection->setPageSize(5);
                $collection->setCurPage(2);
                $size = $collection->getSize();
                $cnt = count($collection);
                foreach ($collection as $item) {
                    $i = $i+1;
                    $item->setTitle($i);
                    echo $item->getTitle();
                }

                $collection->walk('save');
                */
                
                /*
                    This shows how to load a single record and save a change.
                    1) Note the setTitle, this corresponds to the table field name, title, and then you pass it the text to change.
                    2) Call the save() function only on a single record.
                */
                /*
                $object = Mage::getModel('nsu/nsu')->load(1);
                $object->setTitle('This is a changed title');
                $object->save();
				*/

            ?> 